name: a better place to be
favicon: null
layout_spectrum: 0.57095
typography_spectrum: 0.46323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#004871'
    - '#009ace'
    - '#6dc5e4'
    - '#437596'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
